### ISSUE TITLE
Use octokit API to add descriptions to labels

### ISSUE THREAD

**Issue by develohpanda** [mheap/github-action-issue-management#8]
This action was recently enabled on https://github.com/Kong/insomnia, and I noticed the `necromancer` label was added onto an issue. It appears the README for this action does not document what this label means but it does serve a purpose as per the code implementation. It would be very useful for this action to also add descriptions explaining the purpose of each label it creates in a repository.

Reference: https://octokit.github.io/rest.js/v18#issues-create-label

**Comment by mheap** [comment]
Thanks for the catch! Now that I've reviewed the code I think that there's actually a bug as it doesn't check if the poster is a collaborator.

What do you think would be more useful?

1. Only apply the label if the poster is not a team member
2. Only apply the label if more than 7 days have passed since it was closed
3. Both options 1 and 2

I'll update the README to cover this too

**Comment by develohpanda** [comment]
What purpose does the `necromancer` label serve specifically? My understanding is that it is applied when an issue has been closed and some reasoning given as to why. Is that right?

**Comment by mheap** [comment]
https://github.com/mheap/github-action-issue-management/releases/tag/v1.1.0 just went out with this functionality. If you add a `workflow_dispatch` trigger to your action you can use it to sync label colours + descriptions
